[package]
name = "llm-consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
env_logger = "0.11.6"
jemini = "0.1.1"
log = "0.4.22"
rand = "0.8.5"
reqwest = {version = "0.12.9", features = ["json"]}
serde = {version = "1.0.215", features = ["derive"]}
tokio = "1.41.1"
